key: 
    build: . 
    command: gunicorn --name key -b 0.0.0.0:5488 -w 2 wsgi:app
    env_file: 
        - key.env
    ports: 
        - "5488:5488" 
    links: 
        - redis1 

redis1:
    image: redis
    command: redis-server --port 6662
    ports:
        - "6662:6662"
