#!/usr/bin/env python
# encoding: utf-8

from flask import jsonify, request
from . import  api
import redis
rds = redis.StrictRedis(host='localhost',port=6666,db=1)

@api.route('/key/',methods=['POST'])
def key() :
    keys = request.get_json().get('keyword')
    res = rds.hgetall(keys)
    res.append("keys":keys)
    group = res['group']

    return jsonify({ 'msg' : res }) , 200

